---
inherit_from:
  - https://relaxed.ruby.style/rubocop.yml

AllCops:
  Exclude:
    - bin/*
    - db/schema.rb
    - spec/dummy/**/*
    - vendor/**/*
  NewCops: enable

Gemspec/RequiredRubyVersion:
  Enabled: false

Naming/FileName:
  Enabled: false

Layout/LineLength:
  Enabled: true
  Max: 120

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true
