version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2

jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.6-stretch-node-browsers
    executor: ruby/default
    steps:
      - checkout
      - restore_cache:
          key: gem-cache-{{ checksum "activeadmin_blaze_theme.gemspec" }}
      - run:
          name: Setup Bundler
          command: gem install bundler
      - run:
          name: Bundle Install
          command: bundle install --path vendor/bundle
      - save_cache:
          key: gem-cache-{{ checksum "activeadmin_blaze_theme.gemspec" }}
          paths: vendor/bundle
      - run:
          name: Run Specs
          command: |
            bin/rspec \
              --profile 10 \
              --format RspecJunitFormatter \
              --out test_results/rspec.xml \
              --format progress \
              $(circleci tests glob "spec/**/*_spec.rb")
      - store_test_results:
          path: test_results